services:
  mysql:
    restart: always
    image: mysql:8.0.31
    container_name: mysql
    ports:
        - "3306:3306"
        - "3306:3306"
    networks:
        - vbo
    environment:
        - MYSQL_ROOT_PASSWORD=berna071
        - MYSQL_ROOT_HOST="%"
    volumes:
        - mysql_data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password    
    # command: --init-file=/tmp/reset-password.sql
    # command: --skip-grant-tables
  postgresql:
    restart: always
    image: postgres:15
    container_name: postgresql
    ports:
      - "5432:5432"
    networks:
      - vbo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=berna071
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    mysql_data:
    postgres_data:
networks:
  vbo: